### ISSUE TITLE
Automate packaging and release of new versions

### ISSUE THREAD

**Issue by teodor-ande-elstad** [hafslundnett/hdd-style#92]
The [release-build](https://hafslundtfs.visualstudio.com/Hafslund%20Nett/Hafslund%20Nett%20Team/_build?definitionId=683&_a=summary) only handles upload of files to Azure CDN, but it could potentially handle the packaging and release of a new version as well. By doing this as part of the build, we could automate updating package-version and CDN-url based on the release-branch number, reducing the number of manual operations needed to roll out a new version.

**Comment by JGH153** [comment]
Fixed with github action (based on package number)
